"""Shared filesystem locations for the lightweight NBA data pipeline."""
from __future__ import annotations

from pathlib import Path


ROOT: Path = Path(__file__).resolve().parents[2]
"""Repository root resolved at import time."""


DATA_DIR: Path = ROOT / "data"
"""Top-level data directory used for all pipeline artefacts."""


RAW_DIR: Path = DATA_DIR / "raw"
"""Directory containing raw CSV exports."""


EXTERNAL_DIR: Path = DATA_DIR / "external"
"""Directory used for staging third-party datasets (e.g. Kaggle)."""


WYATT_DATASET_DIR: Path = EXTERNAL_DIR / "wyatt"
"""Location of the wyattowalsh/basketball Kaggle dataset."""


RAW_BOOTSTRAP_DIR: Path = RAW_DIR / "bootstrap"
"""Landing zone for bootstrap tables imported from Kaggle."""


RAW_BOOTSTRAP_LEAGUELOG_DIR: Path = RAW_BOOTSTRAP_DIR / "leaguegamelog"
"""Location for the bootstrap league game logs derived from Kaggle."""


WATERMARK_PATH: Path = RAW_BOOTSTRAP_DIR / ".watermark"
"""ISO date string representing the latest game in the bootstrap dataset."""


GAME_CSV: Path = RAW_DIR / "game.csv"
"""Canonical location of the consolidated per-team game log."""


DUCKDB_PATH: Path = DATA_DIR / "nba.duckdb"
"""Canonical DuckDB warehouse location."""


LOG_DIR: Path = ROOT / "logs"
"""Directory for log files generated by the pipeline."""


REPORTS_DIR: Path = ROOT / "reports"
"""Directory containing human-readable run summaries."""


__all__ = [
    "ROOT",
    "DATA_DIR",
    "RAW_DIR",
    "EXTERNAL_DIR",
    "WYATT_DATASET_DIR",
    "RAW_BOOTSTRAP_DIR",
    "RAW_BOOTSTRAP_LEAGUELOG_DIR",
    "WATERMARK_PATH",
    "GAME_CSV",
    "DUCKDB_PATH",
    "LOG_DIR",
    "REPORTS_DIR",
]
