CREATE OR REPLACE VIEW silver.box_score_team_norm AS
WITH bx AS (
  SELECT
    LPAD(CAST(game_id AS VARCHAR), 10, '0') AS game_id,
    TRY_CAST(NULLIF(CAST(game_sequence AS VARCHAR), '') AS INTEGER) AS game_sequence,
    TRY_CAST(NULLIF(CAST(game_date_est AS VARCHAR), '') AS DATE) AS game_date,
    CAST(NULLIF(TRIM(CAST(team_id_home AS VARCHAR)), '') AS VARCHAR) AS team_id_home,
    CAST(NULLIF(TRIM(CAST(team_abbreviation_home AS VARCHAR)), '') AS VARCHAR) AS team_abbreviation_home,
    CAST(NULLIF(TRIM(CAST(team_city_name_home AS VARCHAR)), '') AS VARCHAR) AS team_city_home,
    CAST(NULLIF(TRIM(CAST(team_nickname_home AS VARCHAR)), '') AS VARCHAR) AS team_nickname_home,
    CAST(NULLIF(TRIM(CAST(team_wins_losses_home AS VARCHAR)), '') AS VARCHAR) AS team_wins_losses_home,
    TRY_CAST(NULLIF(CAST(pts_qtr1_home AS VARCHAR), '') AS DOUBLE) AS pts_q1_home,
    TRY_CAST(NULLIF(CAST(pts_qtr2_home AS VARCHAR), '') AS DOUBLE) AS pts_q2_home,
    TRY_CAST(NULLIF(CAST(pts_qtr3_home AS VARCHAR), '') AS DOUBLE) AS pts_q3_home,
    TRY_CAST(NULLIF(CAST(pts_qtr4_home AS VARCHAR), '') AS DOUBLE) AS pts_q4_home,
    TRY_CAST(NULLIF(CAST(pts_ot1_home AS VARCHAR), '') AS DOUBLE) AS pts_ot1_home,
    TRY_CAST(NULLIF(CAST(pts_ot2_home AS VARCHAR), '') AS DOUBLE) AS pts_ot2_home,
    TRY_CAST(NULLIF(CAST(pts_ot3_home AS VARCHAR), '') AS DOUBLE) AS pts_ot3_home,
    TRY_CAST(NULLIF(CAST(pts_ot4_home AS VARCHAR), '') AS DOUBLE) AS pts_ot4_home,
    TRY_CAST(NULLIF(CAST(pts_ot5_home AS VARCHAR), '') AS DOUBLE) AS pts_ot5_home,
    TRY_CAST(NULLIF(CAST(pts_ot6_home AS VARCHAR), '') AS DOUBLE) AS pts_ot6_home,
    TRY_CAST(NULLIF(CAST(pts_ot7_home AS VARCHAR), '') AS DOUBLE) AS pts_ot7_home,
    TRY_CAST(NULLIF(CAST(pts_ot8_home AS VARCHAR), '') AS DOUBLE) AS pts_ot8_home,
    TRY_CAST(NULLIF(CAST(pts_ot9_home AS VARCHAR), '') AS DOUBLE) AS pts_ot9_home,
    TRY_CAST(NULLIF(CAST(pts_ot10_home AS VARCHAR), '') AS DOUBLE) AS pts_ot10_home,
    TRY_CAST(NULLIF(CAST(pts_home AS VARCHAR), '') AS DOUBLE) AS pts_home,
    CAST(NULLIF(TRIM(CAST(team_id_away AS VARCHAR)), '') AS VARCHAR) AS team_id_away,
    CAST(NULLIF(TRIM(CAST(team_abbreviation_away AS VARCHAR)), '') AS VARCHAR) AS team_abbreviation_away,
    CAST(NULLIF(TRIM(CAST(team_city_name_away AS VARCHAR)), '') AS VARCHAR) AS team_city_away,
    CAST(NULLIF(TRIM(CAST(team_nickname_away AS VARCHAR)), '') AS VARCHAR) AS team_nickname_away,
    CAST(NULLIF(TRIM(CAST(team_wins_losses_away AS VARCHAR)), '') AS VARCHAR) AS team_wins_losses_away,
    TRY_CAST(NULLIF(CAST(pts_qtr1_away AS VARCHAR), '') AS DOUBLE) AS pts_q1_away,
    TRY_CAST(NULLIF(CAST(pts_qtr2_away AS VARCHAR), '') AS DOUBLE) AS pts_q2_away,
    TRY_CAST(NULLIF(CAST(pts_qtr3_away AS VARCHAR), '') AS DOUBLE) AS pts_q3_away,
    TRY_CAST(NULLIF(CAST(pts_qtr4_away AS VARCHAR), '') AS DOUBLE) AS pts_q4_away,
    TRY_CAST(NULLIF(CAST(pts_ot1_away AS VARCHAR), '') AS DOUBLE) AS pts_ot1_away,
    TRY_CAST(NULLIF(CAST(pts_ot2_away AS VARCHAR), '') AS DOUBLE) AS pts_ot2_away,
    TRY_CAST(NULLIF(CAST(pts_ot3_away AS VARCHAR), '') AS DOUBLE) AS pts_ot3_away,
    TRY_CAST(NULLIF(CAST(pts_ot4_away AS VARCHAR), '') AS DOUBLE) AS pts_ot4_away,
    TRY_CAST(NULLIF(CAST(pts_ot5_away AS VARCHAR), '') AS DOUBLE) AS pts_ot5_away,
    TRY_CAST(NULLIF(CAST(pts_ot6_away AS VARCHAR), '') AS DOUBLE) AS pts_ot6_away,
    TRY_CAST(NULLIF(CAST(pts_ot7_away AS VARCHAR), '') AS DOUBLE) AS pts_ot7_away,
    TRY_CAST(NULLIF(CAST(pts_ot8_away AS VARCHAR), '') AS DOUBLE) AS pts_ot8_away,
    TRY_CAST(NULLIF(CAST(pts_ot9_away AS VARCHAR), '') AS DOUBLE) AS pts_ot9_away,
    TRY_CAST(NULLIF(CAST(pts_ot10_away AS VARCHAR), '') AS DOUBLE) AS pts_ot10_away,
    TRY_CAST(NULLIF(CAST(pts_away AS VARCHAR), '') AS DOUBLE) AS pts_away
  FROM bronze_box_score_team
)
SELECT
  game_id,
  team_id_home AS team_id,
  'home' AS bx_side,
  game_date AS bx_game_date,
  game_sequence AS bx_game_sequence,
  team_abbreviation_home AS bx_team_abbreviation,
  team_city_home AS bx_team_city,
  team_nickname_home AS bx_team_nickname,
  team_wins_losses_home AS bx_team_wins_losses,
  pts_q1_home AS bx_pts_q1,
  pts_q2_home AS bx_pts_q2,
  pts_q3_home AS bx_pts_q3,
  pts_q4_home AS bx_pts_q4,
  pts_ot1_home AS bx_pts_ot1,
  pts_ot2_home AS bx_pts_ot2,
  pts_ot3_home AS bx_pts_ot3,
  pts_ot4_home AS bx_pts_ot4,
  pts_ot5_home AS bx_pts_ot5,
  pts_ot6_home AS bx_pts_ot6,
  pts_ot7_home AS bx_pts_ot7,
  pts_ot8_home AS bx_pts_ot8,
  pts_ot9_home AS bx_pts_ot9,
  pts_ot10_home AS bx_pts_ot10,
  pts_home AS bx_pts
FROM bx
UNION ALL
SELECT
  game_id,
  team_id_away AS team_id,
  'away' AS bx_side,
  game_date AS bx_game_date,
  game_sequence AS bx_game_sequence,
  team_abbreviation_away AS bx_team_abbreviation,
  team_city_away AS bx_team_city,
  team_nickname_away AS bx_team_nickname,
  team_wins_losses_away AS bx_team_wins_losses,
  pts_q1_away AS bx_pts_q1,
  pts_q2_away AS bx_pts_q2,
  pts_q3_away AS bx_pts_q3,
  pts_q4_away AS bx_pts_q4,
  pts_ot1_away AS bx_pts_ot1,
  pts_ot2_away AS bx_pts_ot2,
  pts_ot3_away AS bx_pts_ot3,
  pts_ot4_away AS bx_pts_ot4,
  pts_ot5_away AS bx_pts_ot5,
  pts_ot6_away AS bx_pts_ot6,
  pts_ot7_away AS bx_pts_ot7,
  pts_ot8_away AS bx_pts_ot8,
  pts_ot9_away AS bx_pts_ot9,
  pts_ot10_away AS bx_pts_ot10,
  pts_away AS bx_pts
FROM bx;
